import React from 'react';
import {
    Document,
    Page,
    Text,
    View,
    StyleSheet,
    Font,
} from '@react-pdf/renderer';

Font.register({
    family: 'Inter',
    fonts: [
        { src: 'https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hjp-Ek-_EeA.ttf', fontWeight: 'normal' },
        { src: 'https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuI6fAZ9hjp-Ek-_EeA.ttf', fontWeight: 'bold' },
    ],
});

const styles = StyleSheet.create({
    page: { padding: 40, fontFamily: 'Inter', fontSize: 10, color: '#333' },
    header: { marginBottom: 20, borderBottom: 1, borderBottomColor: '#eee', paddingBottom: 10 },
    title: { fontSize: 18, fontWeight: 'bold', marginBottom: 5 },
    tenantInfo: { marginBottom: 20, flexDirection: 'row', justifyContent: 'space-between' },
    table: { width: '100%', borderCollapse: 'collapse' },
    tableHeader: { flexDirection: 'row', backgroundColor: '#f8f9fa', borderBottom: 1, borderBottomColor: '#dee2e6', fontWeight: 'bold', padding: 8 },
    tableRow: { flexDirection: 'row', borderBottom: 1, borderBottomColor: '#eee', padding: 8 },
    colDate: { width: '20%' },
    colDesc: { width: '40%' },
    colAmount: { width: '20%', textAlign: 'right' },
    colBalance: { width: '20%', textAlign: 'right' },
    footer: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', fontSize: 8, color: '#888' },
    summary: { marginTop: 20, borderTop: 1, borderTopColor: '#333', paddingTop: 10, flexDirection: 'row', justifyContent: 'flex-end' },
    summaryLabel: { fontWeight: 'bold', marginRight: 10 },
    summaryValue: { fontWeight: 'bold', color: '#dc2626' },
});

interface LedgerEntry {
    date: string;
    description: string;
    amount: number;
    type: 'debit' | 'credit';
}

interface TenantLedgerProps {
    tenantName: string;
    roomNumber: string;
    buildingName: string;
    entries: LedgerEntry[];
    totalDue: number;
}

export const TenantLedgerPDF = ({
    tenantName,
    roomNumber,
    buildingName,
    entries,
    totalDue,
}: TenantLedgerProps) => {
    return (
        <Document>
            <Page size="A4" style={styles.page}>
                <View style={styles.header}>
                    <Text style={styles.title}>Tenant Ledger Statement</Text>
                    <Text>Building: {buildingName} | Room: {roomNumber}</Text>
                </View>

                <View style={styles.tenantInfo}>
                    <View>
                        <Text style={{ fontWeight: 'bold' }}>Tenant Details:</Text>
                        <Text>{tenantName}</Text>
                    </View>
                    <View style={{ textAlign: 'right' }}>
                        <Text style={{ fontWeight: 'bold' }}>Statement Date:</Text>
                        <Text>{new Date().toLocaleDateString()}</Text>
                    </View>
                </View>

                <View style={styles.table}>
                    <View style={styles.tableHeader}>
                        <Text style={styles.colDate}>Date</Text>
                        <Text style={styles.colDesc}>Description</Text>
                        <Text style={styles.colAmount}>Amount (₹)</Text>
                        <Text style={styles.colBalance}>Type</Text>
                    </View>

                    {entries.map((entry, i) => (
                        <View key={i} style={styles.tableRow}>
                            <Text style={styles.colDate}>{entry.date}</Text>
                            <Text style={styles.colDesc}>{entry.description}</Text>
                            <Text style={styles.colAmount}>{entry.amount.toLocaleString()}</Text>
                            <Text style={[styles.colBalance, { color: entry.type === 'debit' ? '#dc2626' : '#16a34a' }]}>
                                {entry.type === 'debit' ? 'Billed' : 'Paid'}
                            </Text>
                        </View>
                    ))}
                </View>

                <View style={styles.summary}>
                    <Text style={styles.summaryLabel}>Outstanding Balance:</Text>
                    <Text style={styles.summaryValue}>₹{totalDue.toLocaleString()}</Text>
                </View>

                <Text style={styles.footer}>
                    Generated by RentFlow • This is a computer-generated statement.
                </Text>
            </Page>
        </Document>
    );
};

export default TenantLedgerPDF;
